### ISSUE TITLE
Class Cl_StrengthStats

### ISSUE THREAD

**Issue by jonsy92** [jonsy92/fitraspi#5]

**Comment by jonsy92** [comment]
Viel Erfolg! ;)

**Comment by Daniel10S** [comment]
Geplant zu implementieren sind:
Properties (squats, benchpress, etc.)
Getter und setter 
Methoden zum errechnen des maximalgewichts
Haste noch was?

**Comment by Daniel10S** [comment]
So hab gepushed;)
Hau raus falls dir was nich gefällt, oder du noch Ergänzungen hast😉😘

**Comment by Daniel10S** [comment]
Sorry falscher Button 😅

**Comment by jonsy92** [comment]
hab mal noch die überflüssigen Parameter und Methoden gelöscht und schließe das issue jetzt :)
